### ISSUE TITLE
Bytemd + Nuxt bundle file too large

### ISSUE THREAD

**Issue by venson** [pd4d10/hashmd#228]
1. nuxt 2.15.8
2. bytemd 1.17.2

problem
1. The bundle size that from bytemd is way to big.
2. @icon-park/svg, mermaid, katex take the top 3 space.

Please help
Is there a way to ruduce the bundle size?

**Comment by 0gust1** [comment]
I noticed that there are several occurrences of `import * as icons from '@icon-park/svg'` in byteMD source code
(see https://github.com/bytedance/bytemd/search?q=import+*+as+icons). 

I guess it would not be correctly tree-shaken when building. 

The mermaid plugin is also **really** heavy (on our side we won't use it, so we will disable the plugin import)

**Comment by 0gust1** [comment]
@venson I made a PR to improve the icon set tree shaking for build engines. You can give a look.

**Comment by weijiatan456** [comment]
![image](https://user-images.githubusercontent.com/12267829/206136263-c586279d-d1cd-4b2e-a9c4-3ad1fb4637ff.png)

I also encountered the same problem, it was very large after packing.

**Comment by 0gust1** [comment]
@weijiatan456 could you try with https://github.com/bytedance/bytemd/pull/236 ? 

If your bundler (webpack/rollup/vite/parcel etc.) is well configured, it should decrease **a lot** the weight of your `systemEditQuestion` and `systemQuestionDetail` modules. 

If so 
- post the the resulting graph here
- add a comment or a "like" on my PR. It will help to remind the maintainers to take a look

**Comment by weijiatan456** [comment]
> @weijiatan456 could you try with #236 ?
> 
> If your bundler (webpack/rollup/vite/parcel etc.) is well configured, it should decrease **a lot** the weight of your `systemEditQuestion` and `systemQuestionDetail` modules.
> 
> If so
> 
> * post the the resulting graph here
> * add a comment or a "like" on my PR. It will help to remind the maintainers to take a look

I agree with your modification, but I don't know how to packing it after modification.

**Comment by 0gust1** [comment]
> but I don't know how to packing it after modification.

@weijiatan456

In order to benefit fully, my PR has to be merged in byteMD repository...

But if your project is svelte-based, you can temporarily test it directly in your project:
- open your project and go to `node_modules/bytemd/svelte`
- in this directory, apply the same modifications as in https://github.com/bytedance/bytemd/pull/236/files (there is 6 files to modify)
- run your package analyser again, in order to compare with your previous image. Post the results here.
- Please note that these modifications are temporary (the next time you'll run `npm install`, they will be erased).

**Comment by pd4d10** [comment]
Thanks for the feedback!

> @icon-park/svg, mermaid, katex take the top 3 space.

The `mermaid` should be a lazy chunk, which would only be loaded if the content has mermaid diagram. So does the `katex` if you are using `plugin-math` instead of `plugin-math-ssr`

For the icons part, we can discuss it at @0gust1 's PR https://github.com/bytedance/bytemd/pull/236#issuecomment-1345147802

**Comment by pd4d10** [comment]
Hi all, just published the latest v1.20.0 to fix this. In a8b4c9a5c90fb4c31d5bea189d77d63498cc69e6 we extract the icons we used to separated files instead of importing icons directly from the package

Please give it a try.

Thanks for all the feedback!
