### ISSUE TITLE
Feature Request: Code block highlight for the editor

### ISSUE THREAD

**Issue by gudh** [pd4d10/hashmd#237]
First of all, thanks for building this amazing markdown editor, absolutely love it ❤️

I wonder is it possible to highlight code block directly in the editor?

Just like the code in the Viewer https://bytemd.js.org/playground/

![Xnip2022-11-22_20-50-31](https://user-images.githubusercontent.com/3378031/203318400-1dcf07c4-45fa-468b-a87a-67b803e82275.jpg)

Thanks!

**Comment by pd4d10** [comment]
Yeah, it's a good suggestion.

The editor we use under the hood is codemirror@5, I'm not sure if there are ready-made solutions

**Comment by CPunisher** [comment]
It is practical, since language modes in codemirror 5 support nesting other language modes.
See: https://codemirror.net/5/mode/gfm/index.html
The only thing you should do is add `codemirror-ssr` to your dependencies,  importing corresponding language modes and setuping them with the codemirror instance of bytemd. You can achieve it with the help of the plugin system.
Here is an example to highlight a code block of javascript in the editor.
```tsx
import useJavaScript from 'codemirror-ssr/mode/javascript/javascript.js'
const plugins = [
    // ... other plugins
    {
        editorEffect(ctx) {
            useJavaScript(ctx.codemirror)
        }
    },
]

// ... pass plugins prop to editor component
```
![image](https://user-images.githubusercontent.com/8509934/211327438-14847fcc-2c71-4213-a7fb-31d87628d75c.png)

I think it is better to make such a plugin.

**Comment by GuoJikun** [comment]
[@bytemd/plugin-highlight](https://www.npmjs.com/package/@bytemd/plugin-highlight)
