### ISSUE TITLE
Error in using uploadImages

### ISSUE THREAD

**Issue by Wesley1993** [pd4d10/hashmd#279]
> version: 1.20.2
> env: Vue2

![image](https://user-images.githubusercontent.com/24308685/222664707-be4c8ad7-d46b-473d-8212-427ad0bcc136.png)

**Comment by CPunisher** [comment]
In bytemd, `selectFiles` is a function imported from [select-files](https://www.npmjs.com/package/select-files) packages.
I tried `uploadImages` in official vue2 example, but I can't reproduce your error.
Can you provide a reproduction ?

**Comment by hhuangxm** [comment]
i had the same bug

vue version 2.6.11

**Comment by xSteven7** [comment]
> In bytemd, `selectFiles` is a function imported from [select-files](https://www.npmjs.com/package/select-files) packages. I tried `uploadImages` in official vue2 example, but I can't reproduce your error. Can you provide a reproduction ?

official vue2 example works, the vue-nuxtjs example can reproduce.

**Comment by 15079698746** [comment]
使用vue2 需将 @bytemd/vue 降低到1.17.1 版本，点击上传图片可正常使用

**Comment by CPunisher** [comment]
It seems that there is something wrong with Webpack 4 when the code mixes commonjs and esm, i.e., webpack 4 transpile `select-files` to `Module { default: function }` instead of `function`, which causes this error.
![image](https://user-images.githubusercontent.com/8509934/235301338-21045cf2-8745-4fd7-a71b-a966b917e1c0.png)

Some issues related to webpack v4: 
https://github.com/vuejs/pinia/issues/675
https://github.com/webpack/webpack/issues/6459
https://github.com/webpack/webpack/issues/9509

I have come up with 3 solutions just for reference.
1. Upgrade your webpack to v5
2. Manually resolve all packages resolved as commonjs to corresponding esm file using aliases.
```js
resolve: {
  alias: {
    bytemd$: path.resolve(__dirname, 'node_modules/bytemd/dist/index.mjs'),
    'tippy.js$': path.resolve(__dirname, 'node_modules/tippy.js/dist/tippy.esm'),
  }
}
```
3. Force the use of commonjs by adding the following webpack configuration. Webpack v4 prefer to use `module` field(which points to esm file) in `package.json`(which points to cjs file) to the `main` field, thus exchanging their order can give priority to parsing their cjs files.
```js
resolve: {
  mainFields: ['main', 'module']
}
```

I'm not sure the above solutions work, and welcome better solutions or in-depth discussions.
