### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by heshdotcc** [pd4d10/hashmd#6]
- [x] Installation and Usage instructions

For some reason it requires `@icon-park/svg` to be installed. This may be an issue related to the bundle manager.

- [ ] Fix Svelte/Sapper examples

They cannot compile, since it seems codebase imports dependencies which are not listed in the package.json...

Maybe any [linked lib](https://docs.npmjs.com/cli/link) were used on localhost before code push?

- [x] Provide an updated example with Rollup

1. It will require both [JSON](https://github.com/rollup/plugins/tree/master/packages/json) and [CSS](https://github.com/egoist/rollup-plugin-postcss) Rollup plugins.

1. As seen in #3:

_This may require the introduction of `rollup-plugin-node-globals` and `rollup-plugin-node-builtins` to correctly handle some dependent Node.js built-in modules._

Installing [rollup-plugin-node-polyfills](https://github.com/ionic-team/rollup-plugin-node-polyfills) and calling it as a plugin solves the issue.

**Comment by pd4d10** [comment]
Hi, @fchpr, thanks for the report.

> it requires @icon-park/svg to be installed

It has been fixed in the latest v0.1.9. `@icon-park/svg` is a dependency now, and no need to install it manually.

> Svelte/Sapper examples

Do you mean the example at `examples/svelte-ssr`? This is probably related to the first issue and should have been fixed now.

> Provide an updated example with Rollup

That's a great point. I've notice that some efforts have been made, would you like to send a PR? I think adding a `examples/svelte-rollup` would be great.

**Comment by pd4d10** [comment]
Hi, @fchpr , Rollup example has been updated, which may solve some of the problems you reported.

See https://github.com/bytedance/bytemd/tree/main/examples/svelte-rollup

**Comment by pd4d10** [comment]
Since the Sapper project seems to be [discontinued](https://svelte.dev/blog/whats-the-deal-with-sveltekit),  I'm going to close this issue.

We also provide an example of its successor SvelteKit, see [here](https://github.com/bytedance/bytemd/tree/main/examples/svelte-kit).
